services:
  todo:
    build: .
    container_name: todo-app
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=postgresql://<username>:<password>@10.0.2.22:5432/todos
      - SECRET_KEY=change-me-to-something-random-later
